- name: Build Image
  run: docker build -t ${{ secrets.DOCKER_USERNAME }}/myapp:${{ github.sha }} .

- name: Tag latest
  run: docker tag ${{ secrets.DOCKER_USERNAME }}/myapp:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/myapp:latest

- name: Push Version Tag
  run: docker push ${{ secrets.DOCKER_USERNAME }}/myapp:${{ github.sha }}

- name: Push Latest Tag
  run: docker push ${{ secrets.DOCKER_USERNAME }}/myapp:latest