name: Auto Deploy with Rollback

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # 🔥 BUILD WITH UNIQUE VERSION (ROLLBACK ENABLED)
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/myapp:${{ github.sha }} .

      # 🔥 PUSH IMAGE
      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/myapp:${{ github.sha }}

      - name: Debug EC2 Key
        run: |
          if [ -z "${{ secrets.EC2_KEY }}" ]; then
            echo "❌ KEY IS EMPTY"
          else
           echo "✅ KEY IS PRESENT"
          fi
    
    # 🔥 DEPLOY ON EC2
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/myapp:${{ github.sha }}
            docker rm -f $(docker ps -aq) || true
            docker run -d -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/myapp:${{ github.sha }}